name: Server
on:
  workflow_dispatch:
  push:
    branches: [ "2.1" ]
  pull_request:
    branches: [ "2.1" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote SSH commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT}}
        script: |
          cd /www/wwwroot/crm.lionsfortco.com/crm
          eval `ssh-agent -s`
          ssh-add /root/.ssh/id_rsa
          ssh -T git@github.com
          git config --global --add safe.directory /www/wwwroot/crm.lionsfortco.com/crm
          git reset --hard origin/ma2.1in
          git fetch origin
          git checkout 2.1
          git pull origin 2.1
          composer install
          composer dump-autoload
          php artisan cache:clear && php artisan route:clear && php artisan config:clear && php artisan view:clear && php artisan event:clear